version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    # image: digitalocean.com/php
    container_name: laravel-api001-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: laravel-api001-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./laravel-app:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-api001-app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-api001-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8083:80"
      # - "443:443"
    volumes:
      - ./laravel-app:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel-api001-app-network

  #MySQL Service
  db:
    image: mysql:8.0
    container_name: laravel-api001-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    tty: true
#    ports:
#      - "3306:3306"
    ports: [3306]
    environment:
      MYSQL_DATABASE: laravel_api001_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
    volumes:
      - laravel-api001-dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-api001-app-network

#Docker Networks
networks:
  laravel-api001-app-network:
    driver: bridge

#Volumes
volumes:
  laravel-api001-dbdata:
    driver: local